name: Terraform Destroy AWS Resources

on:
  workflow_dispatch:   # Se poate lansa manual din GitHub UI
  # Sau poți adăuga alte trigger-e, ex: push pe un branch specific:
  # push:
  #   branches:
  #     - destroy

jobs:
  destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest

    env:
      AWS_DEFAULT_REGION: eu-central-1

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.8.0

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-central-1

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -auto-approve
